# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Crypt-OpenSSL-PKCS10
version:      0.05
version_from: PKCS10.pm
installdirs:  site
requires:
    Crypt::OpenSSL::RSA:           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
